FROM star-sw-test

WORKDIR /tmp/
RUN rm -rf /tmp/star-sw
RUN git clone https://github.com/jdbrice/star-sw.git \
	&& cd /tmp/star-sw \
	&&  git checkout stg-kitrack-genfit 
# COPY target_properties.cmake /tmp/star-sw/cmake/target_properties.cmake

COPY build /tmp/star-build/
RUN chmod +x /tmp/star-build/build

RUN cd /tmp/star-build/ && ./build && make StgMaker -j $(nproc) && make install -j $(nproc)




