FROM star-sw-test

WORKDIR /tmp/star-sw

RUN git checkout stg-kitrack-genfit 

COPY target_properties.cmake /tmp/star-sw/cmake/target_properties.cmake

RUN cd ../star-build/ && cmake /tmp/star-sw -DSTAR_SRC=/tmp/star-cvs -DSTAR_PATCH=gcc540 -DCMAKE_INSTALL_PREFIX=/tmp/star-install -DCERNLIB_ROOT=/cern/2006 -DCMAKE_BUILD_TYPE=Debug && make -j $(nproc) && make install

COPY build /tmp/star-build/
RUN chmod +x /tmp/star-build/build


